开发/src/fjtc/fjtc.com/Areas/Admin/Controllers/MpRedPackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using fjtc.com.Areas.Admin.Models;
using fjtc.com.Common;
using Fjtc.BLL;
using Fjtc.BLL.MpWeiXin;
using Fjtc.Model.Entity;
using Fjtc.Model.SearchModel;
using RPoney;

namespace fjtc.com.Areas.Admin.Controllers
{
    public class MpRedPackController : BaseAdminControl
    {
        // GET: Admin/MpRedPack
        private readonly Lazy<MpWeiXinRedPackLogBll> _mpWeiXinRePackLogBll = new Lazy<MpWeiXinRedPackLogBll>();
        private readonly Lazy<ProductUserBLL> _productUserBll = new Lazy<ProductUserBLL>();

        [HttpGet]
        public ActionResult List(MpWeiXinRedPackLogSearchParameter searchParameter)
        {
            return View(searchParameter);
        }
        [HttpPost]
        public ActionResult List(MpWeiXinRedPackLogSearchParameter searchParameter, FormCollection collection)
        {
            BindParameter(searchParameter);
            searchParameter.ProductUserId = CurrentUser.Id;
            searchParameter.ReturnList = _mpWeiXinRePackLogBll.Value.GetRedPackLog(searchParameter);
            return Json(searchParameter);
        }

        [HttpGet]
        public ActionResult SendRedPack(RedPackModel model)
        {
            return View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult SendRedPack(RedPackModel model, FormCollection collection)
        {
            var productUser = _productUserBll.Value.Get(CurrentUser.Id);
            if (productUser.SendRedPackPassword != productUser.EncryPassword(model.SendRedPackPassword))
            {
                return DwzHelper.Warn("发送红包口令错误");
            }
            //校验
            model.SendRedPackPassword = string.Empty;//密码不能写入日志
            RPoney.Log.LoggerManager.Info(GetType().Name, "发送红包", model.SerializeToJSON());
            var setting = new MpWeiXinAccessSettingBll().GetMpWeiXinAccessSettingByHost(CurrentUser.BindHost);
            var mpUserBll = new MpWeiXinUserBll();
            var errMsg = string.Empty;
            foreach (var item in MakeRedPack(model))
            {
                try
                {
                    var user = mpUserBll.GetBelongMpProductUser(item.MpUserId, CurrentUser.Id);
                    var nonceStr = string.Empty;
                    var paySign = string.Empty;
                    var result = Fjtc.MpWeiXin.TenPayLibV3.RedPackApi.SendNormalRedPack(
                         setting.AppId,
                         setting.MachId,
                         setting.ApiKey,
                         setting.CertPath,
                         user.OpenId,
                         model.SenderName,
                         item.RedPackAmount,
                         model.Wishing,
                         model.ActionName,
                         model.Remark,
                         out nonceStr,
                         out paySign,
                         OrderHelper.GetMachBillno(setting.MachId),
                         model.SceneIdType
                         );
                    RPoney.Log.LoggerManager.Info(GetType().Name, result.SerializeToJSON());
                    if (result.return_code == "SUCCESS")
                    {
                        if (result.result_code == "SUCCESS")
                        {
                            _mpWeiXinRePackLogBll.Value.Add(new MpWeiXinRedPackLogEntity()
                            {
                                CreatedBy = CurrentUser.LoginName,
                                OpenId = result.re_openid,
                                RedPackAmount = Convert.ToInt64(result.total_amount),
                                Remark = $"微信单号：{result.send_listid}",
                                ProductUserId = CurrentUser.Id
                            });
                        }
                        else if (result.result_code == "FAIL")
                        {
                            RPoney.Log.LoggerManager.Info(GetType().Name, $"{result.err_code}:{result.err_code_des}");
                            errMsg += $"发送失败:{ result.err_code}:{ result.err_code_des}{Environment.NewLine}";
                        }
                        else
                        {
                            errMsg += $"未知返回码:{result.result_code}";
                        }
                    }
                    else if (result.return_code == "FAIL ")
                    {
                        RPoney.Log.LoggerManager.Info(GetType().Name, $"{item.MpUserId}发送失败,消息:{result.return_msg}{Environment.NewLine}");
                        errMsg += $"{item.MpUserId}发送失败,消息:{result.return_msg}{Environment.NewLine}";
                    }
                    else
                    {
                        errMsg += $"未知返回码:{result.return_code}";
                    }

                }
                catch (Exception ex)
                {
                    errMsg += $"{item.MpUserId}发送失败,详细请查看日志{Environment.NewLine}";
                    RPoney.Log.LoggerManager.Error(GetType().Name, $"{item.MpUserId}发送红包异常", ex);
                }
            }
            if (!string.IsNullOrWhiteSpace(errMsg))
            {
                return DwzHelper.Warn(errMsg);
            }
            return DwzHelper.Success("发送成功");
        }

        private IList<RedPackItemModel> MakeRedPack(RedPackModel model)
        {
            var totalMoney = model.RedPackTotalAmount.GetValueOrDefault() * 100;//单位换算  元换算成分
            var redpackmoney = Convert.ToInt32(totalMoney);
            var redPackList = new List<RedPackItemModel>();
            var mpUserIds = model.MpUserIds.Split(',');
            switch (model.SendRedPackType)
            {
                case 1://平均
                    redPackList.AddRange(mpUserIds.Select(mpuserId => new RedPackItemModel()
                    {
                        MpUserId = Convert.ToInt64(mpuserId),
                        RedPackAmount = redpackmoney
                    }));
                    break;
                case 2://随机
                    var people = mpUserIds.Length;
                    var min = 1;
                    for (int i = 0; i < people; i++)
                    {
                        int leftPeople = people - i;
                        var avg = (redpackmoney * 1.00) / leftPeople;
                        //随机计算
                        var afgFloor = Convert.ToInt32(Math.Floor(Convert.ToDouble(avg)));
                        var redPackItem = new RedPackItemModel()
                        {
                            MpUserId = Convert.ToInt64(mpUserIds[i]),
                        };
                        if (leftPeople == 1)
                        {
                            redPackItem.RedPackAmount = redpackmoney;
                        }
                        else
                        {
                            var randomTime = new Random(leftPeople);
                            var time = randomTime.Next(1, leftPeople - 1);
                            var random = new Random(afgFloor * leftPeople);
                            var ranValue = random.Next(1, afgFloor * time);
                            redPackItem.RedPackAmount = ranValue;
                            redpackmoney = redpackmoney - ranValue;
                        }
                        redPackList.Add(redPackItem);
                    }
                    break;
            }
            return redPackList;
        }
    }
}

开发/src/fjtc/fjtc.com/Areas/Admin/Controllers/MpUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using fjtc.com.Common;
using Fjtc.BLL.MpWeiXin;
using Fjtc.Model.Entity;
using Fjtc.Model.SearchModel;
using Senparc.Weixin;

namespace fjtc.com.Areas.Admin.Controllers
{
    public class MpUserController : BaseAdminControl
    {
        // GET: Admin/MpUser

        private readonly Lazy<MpWeiXinUserBll> _mpWeiXinUserBll = new Lazy<MpWeiXinUserBll>();

        [HttpGet]
        public ActionResult List(MpWeiXinUserSerachParameter serachParameter)
        {
            return View(serachParameter);
        }
        [HttpPost]
        public ActionResult List(MpWeiXinUserSerachParameter serachParameter, FormCollection collection)
        {
            BindParameter(serachParameter);
            serachParameter.ProductUserId = CurrentUser.Id;
            serachParameter.ReturnList = new MpWeiXinUserBll().GetList(serachParameter);
            return Json(serachParameter);
        }
        [HttpPost]
        public ActionResult SyncUserInfoData(string nextOpenId)
        {
            var success = 0;
            var fail = 0;
            var message = string.Empty;
            var result = Fjtc.MpWeiXin.AdvancedAPIs.UserApi.Get(AccessToken().access_token, nextOpenId);
            if (result.errcode == ReturnCode.请求成功)
            {
                if (result.data.openid.Any())
                {
                    foreach (var openId in result.data.openid)
                    {
                        var weiXinUser = Fjtc.MpWeiXin.CommonAPIs.CommonApi.GetUserInfo(AccessToken().access_token, openId);
                        if (_mpWeiXinUserBll.Value.Save(new MpWeiXinUser()
                        {
                            OpenId = weiXinUser.openid,
                            Subscribe = weiXinUser.subscribe,
                            NickName = weiXinUser.nickname,
                            Sex = weiXinUser.sex,
                            City = weiXinUser.city,
                            Country = weiXinUser.country,
                            Province = weiXinUser.province,
                            Language = weiXinUser.language,
                            HeadImgUrl = weiXinUser.headimgurl,
                            SubscribeTime = weiXinUser.subscribe_time,
                            UnionId = weiXinUser.unionid,
                            Remark = weiXinUser.remark,
                            GroupId = weiXinUser.groupid,
                            ProductUserId = CurrentUser.Id
                        }))
                        {
                            success++;
                            message += $"{openId}同步成功";
                        }
                        else
                        {
                            fail++;
                            message += $"{openId}同步失败";
                        }
                    }
                    RPoney.Log.LoggerManager.Debug(GetType().Name, $"同步记录:{message}");
                }
            }
            return DwzHelper.Success($"同步成功：{success}条,同步失败：{fail}条");
        }

        /// <summary>
        /// 同步新关注用户
        /// </summary>
        /// <param name="nextOpenId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SyncNewUserInfoData(string nextOpenId)
        {
            var success = 0;
            var fail = 0;
            var message = string.Empty;
            var result = Fjtc.MpWeiXin.AdvancedAPIs.UserApi.Get(AccessToken().access_token, nextOpenId);
            if (result.errcode == ReturnCode.请求成功)
            {
                if (result.data.openid.Any())
                {
                    foreach (var openId in result.data.openid)
                    {
                        if (_mpWeiXinUserBll.Value.IsExistOpenId(openId))
                        {
                            continue;
                        }
                        var weiXinUser = Fjtc.MpWeiXin.CommonAPIs.CommonApi.GetUserInfo(AccessToken().access_token, openId);
                        if (_mpWeiXinUserBll.Value.Add(new MpWeiXinUser()
                        {
                            OpenId = weiXinUser.openid,
                            Subscribe = weiXinUser.subscribe,
                            NickName = weiXinUser.nickname,
                            Sex = weiXinUser.sex,
                            City = weiXinUser.city,
                            Country = weiXinUser.country,
                            Province = weiXinUser.province,
                            Language = weiXinUser.language,
                            HeadImgUrl = weiXinUser.headimgurl,
                            SubscribeTime = weiXinUser.subscribe_time,
                            UnionId = weiXinUser.unionid,
                            Remark = weiXinUser.remark,
                            GroupId = weiXinUser.groupid,
                            ProductUserId = CurrentUser.Id
                        }))
                        {
                            success++;
                            message += $"{openId}同步成功";
                        }
                        else
                        {
                            fail++;
                            message += $"{openId}同步失败";
                        }
                    }
                    RPoney.Log.LoggerManager.Debug(GetType().Name, $"同步记录:{message}");
                }
            }
            return DwzHelper.Success($"新增粉丝：{success}条,新增失败：{fail}条");
        }

        [HttpGet]
        public ActionResult SelectMpUser(MpWeiXinUserSerachParameter search)
        {
            BindParameter(search);
            search.IsAll = true;
            search.ProductUserId = CurrentUser.Id;
            search.ReturnList = _mpWeiXinUserBll.Value.GetList(search);
            return View(search);
        }

        /// <summary>
        /// 备注用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult RemarkUser(MpWeiXinUser model)
        {
            return View(model);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RemarkUser(MpWeiXinUser model, FormCollection collection)
        {
            var entity = _mpWeiXinUserBll.Value.Get(model.Id);
            if (entity.ProductUserId != CurrentUser.Id)
            {
                return DwzHelper.Warn("非法操作");
            }
            entity.Remark = model.Remark;
            var result=_mpWeiXinUserBll.Value.RemarkUser(entity);
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "备注完成");
            }
            return DwzHelper.Warn("备注异常");
        }
    }
}

开发/src/fjtc/fjtc.com/Areas/Admin/Views/MpRedPack/List.cshtml
@model Fjtc.Model.SearchModel.MpWeiXinRedPackLogSearchParameter
    @{
        Layout = null;
        var tableId = Guid.NewGuid().ToString().Replace("-", "");
        var pagerId = Guid.NewGuid().ToString().Replace("-", "");
        var formId = Guid.NewGuid().ToString().Replace("-", "");
    }
    <div class="pageHeader">
        <form id="@formId" onsubmit="return navTabSearch(this);" action="@Url.Action("List")" method="post">
            @Html.Partial("_Pager", Model)
            <div class="searchBar">
                <table class="searchContent">
                    <tr>
                        <td>
                            用户：@Html.TextBoxFor(m => m.MpUserNick)
                        </td>
                        <td>
                            发送时间：
                            <input id="mp_user_list_begintime" name="BeginSearchTime" class="Wdate" type="text" value="@Model.BeginSearchTime" onFocus="WdatePicker({ dateFmt:'yyyy-MM-dd HH:mm',maxDate: '#F{$dp.$D(\'mp_user_list_endtime\')}' })" />
                            -<input id="mp_user_list_endtime" name="EndSearchTime" class="Wdate" type="text" value="@Model.EndSearchTime" onFocus="WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm', minDate: '#F{$dp.$D(\'mp_user_list_begintime\')}' })" />
                        </td>
                    </tr>
                </table>
            </div>
            <div class="subBar">
                <ul>
                    <li><div class="buttonActive"><div class="buttonContent"><button type="button" onclick="Search()">查询</button></div></div></li>
                </ul>
            </div>
        </form>
    </div>
    <div class="pageContent">
        <div class="panelBar">
            <ul class="toolBar">
                <li><a class="add" href="@Url.Action("SendRedPack")"  target="dialog" width="800" height="480"><span>发送红包</span></a></li>
            </ul>
        </div>
        <table id="@tableId"></table>
        <div id="@pagerId"></div>
    </div>
    <script>
        function InitGrid() {
            $("#@tableId").jqGrid({
                url: '@Url.Action("List")',
                mtype: 'post',
                datatype: "json",
                colModel: [
                    { label: 'Id', name: 'Id', width: '50px', align: 'center', sortable: false },
                    { label: '用户', name: 'MpUserNick', width: '240px' },
                    { label: '红包金额(元)', name: 'RedPackAmount', align: 'center', width: '150px', formatter: MoneyFenToYuan },
                    { label: '发送时间', name: 'CreatedTime', align: 'center', formatter: JsonDateFormat },
                    { label: '说明', name: 'Remark', align: 'center', width: '350px' }
                ],
                rowNum: 10,
                rowList: [10, 50, 100],
                //autowidth: false,
                width: '100%',
                height: '375px',
                prmNames: jqGridDefaultConfig.prmNames,
                jsonReader: jqGridDefaultConfig.jsonReader,
                postData: FormToJson({ formId: '@formId' }),
                pager: '#@pagerId',
                viewrecords: true,
                caption: "红包记录"
            }).navGrid("#@tableId", { edit: false, add: false, del: false });
        }

        function Search() {
            $("#@tableId").jqGrid('setGridParam', { page: 1, postData: FormToJson({ formId: '@formId' }) }).trigger("reloadGrid");
        }
        $(function () {
            InitGrid();
        });
    </script>

开发/src/fjtc/fjtc.com/Areas/Admin/Views/MpRedPack/SendRedPack.cshtml
@{
    Layout = null;
}
@using cms.rponey.cc.Utilty.Extend
@using fjtc.com.Areas.Admin.Models
@model fjtc.com.Areas.Admin.Models.RedPackModel
<div class="pageContent">
    <form method="post" action="@Url.Action("SendRedPack", new { area = "Admin" })" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone);">
        <div class="pageFormContent nowrap" layoutH="60">
            @Html.AntiForgeryToken()
            <dl>
                <dt>活动名称：</dt>
                <dd>
                    @Html.TextBoxFor(m => m.ActionName, new { @class = "required" })
                    <span class="info"></span>
                </dd>
            </dl>
            <dl>
                <dt>红包金额：</dt>
                <dd>
                    @Html.TextBoxFor(m => m.RedPackTotalAmount, new { @class = "number" })元
                    <span class="info"></span>
                </dd>
            </dl>
            <dl>
                <dt>发放方式：</dt>
                <dd>
                    <input type="radio" name="SendRedPackType" value="1" checked="checked"/>平均
                    <input type="radio" name="SendRedPackType" value="2"/>随机
                </dd>
            </dl>
            <dl>
                <dt>红包名称：</dt>
                <dd>
                    @Html.TextBoxFor(m => m.SenderName, new { @class = "required" })
                    <span class="info"></span>
                </dd>
            </dl>
            <dl>
                <dt>场景：</dt>
                <dd>
                    <select name="SceneIdType">
                        @foreach (var scene in EnumExtend.GetEnumRemarks<SceneIdTypeEnum>())
                        {
                            <option value="@scene.Key">@scene.Value</option>
                        }
                    </select>
                </dd>
            </dl>
            <dl>
                <dt>祝福语：</dt>
                <dd>
                    @Html.TextBoxFor(m => m.Wishing, new { @class = "required" })
                    <span class="info"></span>
                </dd>
            </dl>
            <dl>
                <dt>选择发送用户：</dt>
                <dd>
                    @Html.HiddenFor(m => m.MpUserIds)
                    <input id="MpUserNicks" class="required textInput readonly" name="MpUserNicks" type="text" readonly="">
                    <a class="btnLook" target="dialog" mask="true" rel="SelectMpUser" href="javascript:;" onclick="$(this).attr('href', '@Url.Action("SelectMpUser", "MpUser")?SelectedIds=' + $('#MpUserIds').val())" width="800" height="450">选择用户</a>
                </dd>
            </dl>
            <dl>
                <dt>备注信息：</dt>
                <dd>
                    @Html.TextAreaFor(m => m.Remark, new {@class = "required"})
                    <span class="info"></span>
                </dd>
            </dl>
            <dl>
                <dt>发送红包口令：</dt>
                <dd>
                    @Html.PasswordFor(m => m.SendRedPackPassword, new { @class = "required" })
                    <span class="info"></span>
                </dd>
            </dl>
        </div>
        <div class="formBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="submit">确认发送</button></div></div></li>
            </ul>
        </div>
    </form>
</div>
<script>
    window.SelectUserCallback = function (selectIds, selectNames) {
        $("#MpUserIds").val(selectIds);
        $("#MpUserNicks").val(selectNames);
    }
</script>