开发/src/fjtc/admin.fjtc.com/Controllers/CMSRoleController.cs
using System.Web.Mvc;
using admin.fjtc.com.Common;
using Fjtc.BLL;
using Fjtc.Model.Entity;
using Fjtc.Model.SearchModel;
using ServiceStack.Common.Utils;

namespace admin.fjtc.com.Controllers
{
    public class CMSRoleController : BaseController
    {
        // GET: CMSRole

        [HttpGet]
        public ActionResult List(CMSRoleSearchParameter searchParameter)
        {
            BindParameter(searchParameter);
            return View(searchParameter);
        }

        [HttpPost]
        public ActionResult List(CMSRoleSearchParameter searchParameter, FormCollection collection)
        {
            BindParameter(searchParameter);
            searchParameter.ReturnList = new CMSRoleBll().GetList(searchParameter);
            return Json(searchParameter);
        }

        [HttpGet]
        public ActionResult Add(CMSRole model)
        {
            var entity = new CMSRoleBll().Get(model.Id);
            return View(entity ?? model);
        }

        [HttpPost]
        public ActionResult Add(CMSRole model, FormCollection collection)
        {
            var result = false;
            if (model.Id > 0)
            {
                var entity = new CMSRoleBll().Get(model.Id);
                entity.Name = model.Name;
                result = new CMSRoleBll().Update(entity);
            }
            else
            {
                result = new CMSRoleBll().Add(new CMSRole()
                {
                    Name = model.Name,
                    CreatedBy = User.Identity.Name
                });
            }
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "添加成功");
            }
            return DwzHelper.Warn("添加失败");
        }

        [HttpPost]
        public ActionResult Delete(CMSRole model)
        {
            var result = new CMSRoleBll().Delete(model);
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "删除成功");
            }
            return DwzHelper.Warn("删除失败");
        }
    }
}

开发/src/fjtc/admin.fjtc.com/Views/CMSRole/Add.cshtml
@{
    Layout = null;
}
@using Fjtc.Model
@model Fjtc.Model.Entity.CMSRole
<div class="pageContent">
    <form method="post" action="@Url.Action("Add")" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone);">
        <div class="pageFormContent" layoutH="56">
            <p>
                <label>角色：</label>
                @Html.HiddenFor(m=>m.Id)
                @Html.TextBoxFor(m => m.Name)
            </p>
        </div>
        <div class="formBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                <li>
                    <div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
                </li>
            </ul>
        </div>
    </form>
</div>

开发/src/fjtc/admin.fjtc.com/Views/CMSRole/List.cshtml
@model Fjtc.Model.SearchModel.CMSRoleSearchParameter
@{
    Layout = null;
    var tableId = Guid.NewGuid().ToString().Replace("-", "");
    var pagerId = Guid.NewGuid().ToString().Replace("-", "");
    var formId = Guid.NewGuid().ToString().Replace("-", "");
}
<div class="pageHeader">
    <form id="@formId" onsubmit="return navTabSearch(this);" action="@Url.Action("List")" method="post">
        @Html.Partial("_Pager", Model)
        <div class="searchBar">
            <table class="searchContent">
                <tr>
                    <td>
                        角色：@Html.TextBoxFor(m => m.Name)
                    </td>
                </tr>
            </table>
        </div>
        <div class="subBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="button" onclick="Search()">查询</button></div></div></li>
            </ul>
        </div>
    </form>
</div>
<div class="pageContent">
    <div class="panelBar">
        <ul class="toolBar">
            <li><a class="add" href="@Url.Action("Add","CMSRole")?navtab=add" rel="add" target="dialog" title="添加角色" mask="true"><span>添加</span></a></li>
            <li><a class="edit" href="javascript:;" target="dialog" rel="edit" title="编辑角色" mask="true" onclick="Edit(this)"><span>修改</span></a></li>
            <li>
                <a class="delete" href="javascript:;" onclick="Delete()"><span>删除</span></a>
            </li>
        </ul>
    </div>
    <table id="@tableId"></table>
    <div id="@pagerId"></div>
</div>
<script>
    function InitGrid() {
        $("#@tableId").jqGrid({
            url: '@Url.Action("List", "CMSRole")',
            mtype: 'post',
            datatype: "json",
            colNames: ['Id', '角色', '创建人', '创建时间'],
            colModel: [
                { name: 'Id', index: 'Id', hidden: true },
                { name: 'Name', index: 'Name', align: 'center' },
                { name: 'CreatedBy', index: 'CreatedBy', align: 'center' },
                { name: 'CreatedTime', index: 'CreatedTime',align: 'center' }
            ],
            rowNum: 20,
            rowList: [20, 50, 100],
            width: '100%',
            height: '375px',
            prmNames: jqGridDefaultConfig.prmNames,
            jsonReader: jqGridDefaultConfig.jsonReader,
            postData: FormToJson({ formId: '@formId' }),
            pager: '#@pagerId',
            viewrecords: true,
            caption: "角色"
        }).navGrid("#@tableId", { edit: false, add: false, del: false });
    }

    function Search() {
        $("#@tableId").jqGrid('setGridParam', { page: 1, postData: FormToJson({ formId: '@formId' }) }).trigger("reloadGrid");
    }
    function Edit(element) {
        var row = $("#@tableId").jqGrid("getRowData", $("#@tableId").jqGrid('getGridParam', 'selrow'));
        if (row.Id) {
            $(element).attr("href", "@Url.Action("Add", "CMSRole")?navtab=edit&id=" + row.Id);
        }
    }

    function Delete() {
        var row = $("#@tableId").jqGrid("getRowData", $("#@tableId").jqGrid('getGridParam', 'selrow'));
        if (row.Id) {
            alertMsg.confirm("您确定要删除角色"+row.Name+"?", {
                okCall: function () {
                    $.post("@Url.Action("Delete", "CMSRole")?navtab=edit", { Id: row.Id }, DWZ.ajaxDone, "json");
                }
            });
        }
    }
    $(function () {
        InitGrid();
    });
</script>