开发/src/fjtc/admin.fjtc.com/Controllers/BuildController.cs
using System.Web.Mvc;

namespace admin.fjtc.com.Controllers
{
    public class BuildController : Controller
    {
        // GET: Build
        /// <summary>
        /// 网站正在建设中
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return View();
        }
    }
}

开发/src/fjtc/admin.fjtc.com/Controllers/CmsUserController.cs
using System.Web.Mvc;
using admin.fjtc.com.Common;
using Fjtc.BLL;
using Fjtc.Model.Entity;
using Fjtc.Model.SearchModel;
using Fjtc.Model.ViewModel;

namespace admin.fjtc.com.Controllers
{
    public class CMSUserController : BaseController
    {
        /// <summary>
        /// 用户列表页
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult List(CMSUserSearchParameter searchParameter)
        {
            BindParameter(searchParameter);
            return View(searchParameter);
        }

        [HttpPost]
        public ActionResult List(CMSUserSearchParameter searchParameter, FormCollection collection)
        {
            BindParameter(searchParameter);
            searchParameter.ReturnList = new CMSUserBll().GetList(searchParameter);
            return Json(searchParameter);
        }

        [HttpGet]
        public ActionResult Add(CMSUserViewModel user)
        {
            return View(user);
        }

        [HttpPost]
        public ActionResult Add(CMSUserViewModel user, FormCollection collection)
        {
            var result = new CMSUserBll().AddUser(new CMSUser()
            {
                Name = user.Name,
                CreatedBy = User.Identity.Name,
                Password = user.Password,
                Status = user.Status,
                Number = user.Number,
                LoginName = user.LoginName
            });
            if (result)
            {
                return DwzHelper.SuccessAndClose(user.NavTab, "添加成功");
            }
            return DwzHelper.Warn("添加失败");
        }
        [HttpGet]
        public ActionResult Edit(CMSUserViewModel user)
        {
            var userModel = new CMSUserBll().GetModel(user.Id);
            userModel.Password = string.Empty;
            return View(userModel);
        }
        [HttpPost]
        public ActionResult Edit(CMSUserViewModel user, FormCollection collection)
        {
            var result = new CMSUserBll().UpdateUser(user);
            if (result)
            {
                return DwzHelper.SuccessAndClose(user.NavTab, "密码修改成功");
            }
            return DwzHelper.Warn("密码修改失败");
        }

        /// <summary>
        /// 修改密码
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UpdatePassword(CMSUserViewModel model)
        {
            return View(model);
        }
        [HttpPost]
        public ActionResult UpdatePassword(FormCollection collection)
        {
            var password = collection.Get("Password");
            var result = new CMSUserBll().UpdatePassword(
                new CMSUserViewModel()
                {
                    Id = CurrentUser.Id,
                    Password = password
                });
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "密码修改成功");
            }
            return DwzHelper.Warn("密码修改失败");
        }
    }
}

开发/src/fjtc/admin.fjtc.com/Controllers/HomeController.cs
using System.Web.Mvc;
using Fjtc.BLL;

namespace admin.fjtc.com.Controllers
{
    public class HomeController : BaseController
    {
        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.UserMenu = new CMSMenuBll().GetTreeList();
            return View(CurrentUser);
        }
    }
}

开发/src/fjtc/admin.fjtc.com/Views/Home/Index.cshtml
@using Fjtc.Model.Entity
@model Fjtc.Model.Entity.CMSUser
@{
    Layout = null;
    var menuList = ViewBag.UserMenu as IList<CMSMenu>;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>内容管理系统</title>
    <link href='@Url.Content("~/Content/dwz_jui/themes/default/style.css")' rel="stylesheet" type="text/css" media="screen" />
    <link href='@Url.Content("~/Content/dwz_jui/themes/css/core.css")' rel="stylesheet" type="text/css" media="screen" />
    <link href='@Url.Content("~/Content/dwz_jui/themes/css/print.css")' rel="stylesheet" type="text/css" media="print" />
    <link href='@Url.Content("~/Content/uploadify/css/uploadify.css")' rel="stylesheet" type="text/css" media="print" />
    <link href='@Url.Content("~/Content/dwz_jui/themes/css/ieHack.css")' rel="stylesheet" type="text/css" media="screen" />
    <link href="@Url.Content("~/Content/jqGrid/css/ui.jqgrid.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery.ui-1.8.16/jquery-ui.custom.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/speedup.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-2.1.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-migrate-1.2.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.cookie.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.bgiframe.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/uploadify/scripts/jquery.uploadify.js")" type="text/javascript"></script>
    <!-- 可以用dwz.min.js替换前面全部dwz.*.js (注意：替换时下面dwz.regional.zh.js还需要引入) -->
    <script src="@Url.Content("~/Scripts/dwz_jui/dwz.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/dwz_jui/dwz.regional.zh.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/My97DatePicker/WdatePicker.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/lookupExtend.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/AdvancedQuery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Default.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.multi-select.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.quicksearch.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/linq.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.linq.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/doublemultiple.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jqGrid/i18n/grid.locale-cn.js")"></script>
    <script src="@Url.Content("~/Scripts/jqGrid/jqGrid.extend.js")"></script>
    <script src="@Url.Content("~/Scripts/jqGrid/jquery.jqGrid.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            DWZ.init("@Url.Content("~/Content/dwz_jui/dwz.frag.xml")", {
                loginUrl: "@Url.Action("Index", "Account")", loginTitle: "登录",	// 弹出登录对话框
                statusCode: { ok: 200, error: 300, timeout: 301 }, //【可选】
                pageInfo: { pageNum: "pageNum", numPerPage: "numPerPage", orderField: "orderField", orderDirection: "orderDirection" }, //【可选】
                keys: { statusCode: "statusCode", message: "message" }, //【可选】
                ui: { hideMode: 'offsets' }, //【可选】hideMode:navTab组件切换的隐藏方式，支持的值有’display’，’offsets’负数偏移位置的值，默认值为’display’
                debug: false,	// 调试模式 【true|false】
                callback: function () {
                    initEnv();
                    $("#themeList").theme({ themeBase: "/Content/dwz_jui/themes" }); // themeBase 相对于index页面的主题base路径
                }
            });
        });
    </script>
</head>
<body>
    <div id="layout">
        <div id="header">
            <div class="headerNav">
                <ul class="nav">
                    <li><a href="@Url.Action("UpdatePassword","CMSUser")" target="dialog" rel="dialog_updatepassword">修改密码</a></li>
                    <li><a href="@Url.Action("List", "Build")" target="dialog" title="个人信息" rel="dialog_showmyinfo">@(Model.Name + "|" + Model.LoginName)</a></li>
                    <li><a href="@Url.Action("LogOut","Account")">退出</a></li>
                </ul>
                <ul class="themeList" id="themeList">
                    <li theme="default" class="default"><div class="selected">蓝色</div></li>
                    <li theme="green" class="green"><div class="">绿色</div></li>
                    <!--<li theme="red"><div>红色</div></li>-->
                    <li theme="purple" class="purple"><div class="">紫色</div></li>
                    <li theme="silver" class="silver"><div class="">银色</div></li>
                    <li theme="azure" class="azure"><div class="">天蓝</div></li>
                </ul>
            </div>
            <!-- navMenu -->
        </div>
        <div id="leftside">
            <div id="sidebar_s">
                <div class="collapse">
                    <div class="toggleCollapse"><div></div></div>
                </div>
            </div>
            <div id="sidebar">
                <div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>
                <div class="accordion" fillSpace="sidebar">
                   @if (menuList != null)
                   {
                       foreach (var menu in menuList)
                       {
                        <div class="accordionHeader">
                            <h2>
                                <span>Folder</span>@menu.Name
                            </h2>
                        </div>
                        <div class="accordionContent">
                            <ul class="tree treeFolder">
                                @if (menu.Children != null)
                                {
                                    foreach (var child in menu.Children)
                                    {
                                        <li><a href="@(child.Url+"?navtab="+child.OrganPath)" target="navTab" rel="@child.OrganPath">@child.Name</a></li>
                                    }
                                }
                            </ul>
                        </div>
                       }
                   }
                </div>
            </div>
        </div>
        <div id="container">
            <div id="navTab" class="tabsPage">
                <div class="tabsPageHeader">
                    <div class="tabsPageHeaderContent">
                        <!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
                        <ul class="navTab-tab">
                            <li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
                        </ul>
                    </div>
                    <div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
                    <div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
                    <div class="tabsMore">more</div>
                </div>
                <ul class="tabsMoreList">
                    <li><a href="javascript:;">桌面</a></li>
                </ul>
                <div class="navTab-panel tabsPageContent layoutBox">
                    <div class="page unitBox">
                        <div class="pageFormContent" layoutH="80" style="margin-right: 230px">
                            <a href="http://jui.org/" target="navTab" rel="tab100000000">DWZ官网</a>
                            <a href="http://blog.mn886.net/jqGrid/" target="navTab" rel="tab200000000">jqGridApi</a>
                        </div>
                        <div style="width:230px;position: absolute;top:60px;right:0" layoutH="80">
                            <iframe width="100%" height="430" class="share_self" frameborder="0" scrolling="no"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">Copyright &copy; 2010 <a href="javascript:;" target="dialog">17Team团队</a> 京ICP备15053290号-2</div>
</body>
</html>