开发/src/fjtc/fjtc.com/Areas/Admin/Controllers/ProductUserAdminController.cs
using System.Web.Mvc;
using fjtc.com.Common;
using Fjtc.BLL;
using Fjtc.Model.Entity;

namespace fjtc.com.Areas.Admin.Controllers
{
    public class ProductUserAdminController : BaseAdminControl
    {
        // GET: Admin/ProductUserAdmin
        [HttpGet]
        public ActionResult UpdatePassword(ProductUser model)
        {
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdatePassword(ProductUser model, FormCollection collection)
        {
            var result = new ProductUserBLL().UpdatePassword(model.EncryPassword(model.Password), CurrentUser.Id);
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "密码修改成功");
            }
            return DwzHelper.Warn("密码修改失败");
        }

        [HttpGet]
        public ActionResult Index()
        {
            var productUserBll = new ProductUserBLL();
            var user = productUserBll.Get(CurrentUser.Id);
            return View(user);
        }

        [HttpPost]
        public ActionResult Save(ProductUser model)
        {
            var productUserBll = new ProductUserBLL();
            var user = productUserBll.Get(CurrentUser.Id);
            user.SiteName = model.SiteName;
            user.Name = model.Name;
            user.Company = model.Company;
            var result = productUserBll.Update(user);
            if (result)
            {
                return DwzHelper.Success("修改成功");
            }
            return DwzHelper.Warn("修改失败");
        }

        [HttpGet]
        public ActionResult UpdateSendRedPackPassword(ProductUser model)
        {
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateSendRedPackPassword(ProductUser model, FormCollection collection)
        {
            var userBll = new ProductUserBLL();
            var sourceSendRedPackPassword = collection["SourceSendRedPackPassword"];
            var user = userBll.Get(CurrentUser.Id);
            if (user.SendRedPackPassword != model.EncryPassword(sourceSendRedPackPassword))
            {
                return DwzHelper.Warn("原始密码不对");
            }
            var result = userBll.UpdateSendRedPackPassword(model.EncryPassword(model.SendRedPackPassword), CurrentUser.Id);
            if (result)
            {
                return DwzHelper.SuccessAndClose("", "密码修改成功");
            }
            return DwzHelper.Warn("密码修改失败");
        }
    }
}

开发/src/fjtc/fjtc.com/Areas/Admin/Views/ProductUserAdmin/Index.cshtml
@model Fjtc.Model.Entity.ProductUser
@{
    Layout = null;
}
<div class="pageContent">
    <form method="post" action="@Url.Action("Save", new { area = "Admin" })" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone);">
        <div class="pageFormContent" layoutH="180">
            <p>
                <label>昵称：</label>
                @Html.TextBoxFor(m => m.Name)
            </p>
            <p>
                <label>绑定域名：</label>
                @Html.TextBoxFor(m => m.BindHost, new { @readonly = true })
            </p>
            <p>
                <label>网站名称：</label>
                @Html.TextBoxFor(m => m.SiteName)
            </p>
            <p>
                <label>公司名称：</label>
                @Html.TextBoxFor(m => m.Company)
            </p>
            <p>
                <a style="color: blue;" href="@Url.Action("UpdateSendRedPackPassword", "ProductUserAdmin")" target="dialog" rel="dialog_updatepassword">设置发送红包密码</a>
            </p>
        </div>
        <div class="formBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
            </ul>
        </div>
    </form>
</div>

开发/src/fjtc/fjtc.com/Areas/Admin/Views/ProductUserAdmin/UpdatePassword.cshtml
@{
    Layout = null;
}
@model Fjtc.Model.Entity.ProductUser
<div class="pageContent">
    <form method="post" action="@Url.Action("UpdatePassword")" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone);">
        <div class="pageFormContent" layoutH="56">
            <p>
                <label>新密码：</label>
                @Html.TextBoxFor(m => m.Password)
            </p>
        </div>
        <div class="formBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                <li>
                    <div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
                </li>
            </ul>
        </div>
    </form>
</div>

开发/src/fjtc/fjtc.com/Areas/Admin/Views/ProductUserAdmin/UpdateSendRedPackPassword.cshtml
@{
    Layout = null;
}

@{
    Layout = null;
}
@model Fjtc.Model.Entity.ProductUser
<div class="pageContent">
    <form method="post" action="@Url.Action("UpdateSendRedPackPassword")" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone);">
        <div class="pageFormContent" layoutH="56">
            <p style="width: 500px;">
                <label style="width: 250px;">原始发送红包密码（默认登录密码）：</label>
                <input type="password" name="SourceSendRedPackPassword"/>
            </p>
            <p style="width: 500px;">
                <label style="width: 250px;">设置红包支付密码：</label>
                @Html.TextBoxFor(m => m.SendRedPackPassword)
            </p>
        </div>
        <div class="formBar">
            <ul>
                <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                <li>
                    <div class="button"><div class="buttonContent"><button type="button" class="close">取消</button></div></div>
                </li>
            </ul>
        </div>
    </form>
</div>